# Generated by Django 5.0.7 on 2024-08-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogimage_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Комментарии в блоге', 'verbose_name_plural': 'Комментарий в блоге'},
        ),
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='Category', to='blog.categories', verbose_name='Выбрать категорию'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_seen',
            field=models.IntegerField(default=0, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogCommant', to='blog.blog', verbose_name='Блоги'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Объяснение'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное имя фамилия'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogImage', to='blog.blog', verbose_name='Блоги'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название категории'),
        ),
    ]
