# Generated by Django 5.0.7 on 2024-09-12 09:34

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[apps.blog.models.validate_video_size]),
        ),
    ]
