# Generated by Django 5.0.7 on 2024-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='URL-видео'),
        ),
    ]
